// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "sub-my-function-my-topic" {
  source  = "Automatic/hedwig-lambda-subscription/aws"
  version = "~> {{TFLambdaSubscriptionModuleVersion}}"

  function_arn  = "arn:aws:lambda:us-west-2:12345:function:my_function"
  function_name = "my_function"
  topic         = "${module.topic-my-topic.arn}"
}
