// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

variable "aws_account_id" {
  default = "12345"
}

variable "aws_region" {
  default = "us-west-2"
}
