// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "sub-dev-myapp-my-topic" {
  source  = "Automatic/hedwig-queue-subscription/aws"
  version = "~> {{TFQueueSubscriptionModuleVersion}}"

  queue = "${module.consumer-dev-myapp.queue_arn}"
  topic = "${module.topic-my-topic.arn}"
}
